### ISSUE TITLE
Не хватает readme

### ISSUE THREAD

**Issue by WindyLibra** [fshp/cmake-examples#2]
Здравствуйте, я пришёл с вашей статьи на Хабре про CMake. За статью благодарю, однако хотелось бы, что бы в репозитории тут была ссылка на саму статью. 

Так что можете добавить readme с ссылкой на статью?
[README.md](https://github.com/fshp/cmake-examples/files/14881654/README.md)

**Comment by fshp** [comment]
Добавил, спасибо!
